sonar.projectKey=niki22sh_worktime-tracker
sonar.projectName=Worktime Tracker
sonar.projectVersion=1.0.0
sonar.organization=niki22sh

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,coverage/**,reports/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
